functionsDirectory = "/Users/chrisz/.openclaw/workspace/warroom/netlify/functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
publish = "/Users/chrisz/.openclaw/workspace/warroom"
publishOrigin = "config"
functions = "/Users/chrisz/.openclaw/workspace/warroom/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"

[[redirects]]
from = "/api/chat"
to = "/.netlify/functions/chat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/agent-action"
to = "/.netlify/functions/agent-action"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]