functionsDirectory = "/Users/chrisz/.openclaw/workspace/warroom/netlify/functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
publish = "/Users/chrisz/.openclaw/workspace/warroom/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/chrisz/.openclaw/workspace/warroom/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions.apify-scrape]
timeout = 26.0

[functions."*"]
external_node_modules = ["node-fetch"]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"

[[redirects]]
from = "/api/chat"
to = "/.netlify/functions/chat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/agent-action"
to = "/.netlify/functions/agent-action"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/setup"
to = "/.netlify/functions/setup"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/notify"
to = "/.netlify/functions/notify"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/apify-scrape"
to = "/.netlify/functions/apify-scrape"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/unsplash"
to = "/.netlify/functions/unsplash"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]