-- VitalLyfe brand voice seed moved out of canonical migrations.
--
-- Development/non-prod seed SQL now lives in:
--   supabase/seed/dev_seed.sql
--
-- Production rows were already created by the original applied migration; this
-- no-op preserves migration ordering without reseeding tenant data.
